# Sử dụng chính xác image baseline của BTC
FROM vllm/vllm-openai@sha256:953d3a06d5e64ab582985cd7401289d3abf2a2c14ef2158e9a84313daeec77d7

# Copy toàn bộ folder weights vào thư mục /model/ trong container
COPY ./Qwen3.5-2B-BTC /model/